global.questionsets = {
  'Canadian Family Feud 1': [
    { question: "Name a famous Canadian actor.",
      factor: 1,
      answers: [
        { answer: "JIM CARREY",
          score: 24,
        },
        { answer: "MICHAEL J. FOX",
          score: 16,
        },
        { answer: "RYAN GOSLING",
          score: 9,
        },
        { answer: "MIKE MYERS",
          score: 5,
        },
        { answer: "WILLIAM SHATNER",
          score: 4,
        },
        { answer: "RYAN REYNOLDS",
          score: 3,
        },
        { answer: "SETH ROGEN",
          score: 2,
        },
        { answer: "JOHN CANDY",
          score: 2,
        },
      ],
    },
    { question: "What's your favorite thing to do during a blizzard?",
      factor: 1,
      answers: [
        { answer: "DRINK HOT COCOA",
          score: 24,
        },
        { answer: "WATCH TV",
          score: 23,
        },
        { answer: "STAY WARM/BY FIRE",
          score: 11,
        },
        { answer: "READ A BOOK",
          score: 10,
        },
        { answer: "STAY HOME/INSIDE",
          score: 2,
        },
        { answer: "SLEEP",
          score: 2,
        },
        { answer: "EAT COMFORT FOOD",
          score: 2,
        },
      ],
    },
    { question: "Name a province that gets a lot of tourists.",
      factor: 1,
      answers: [
        { answer: "BRITISH COLUMBIA",
          score: 44,
        },
        { answer: "ONTARIO",
          score: 12,
        },
        { answer: "ALBERTA",
          score: 10,
        },
        { answer: "PRINCE EDWARD ISL.",
          score: 5,
        },
        { answer: "NOVA SCOTIA",
          score: 3,
        },
        { answer: "QUEBEC",
          score: 2,
        },
      ],
    },
    { question: "What is something you would find in a Canadian's trunk in the winter.",
      factor: 2,
      answers: [
        { answer: "SHOVEL",
          score: 18,
        },
        { answer: "BOOSTER CABLES",
          score: 15,
        },
        { answer: "SCRAPER",
          score: 13,
        },
        { answer: "BLANKET",
          score: 10,
        },
        { answer: "GLOVES/HATS/BOOTS",
          score: 5,
        },
        { answer: "CHAINS",
          score: 4,
        },
        { answer: "SAND BAGS",
          score: 3,
        },
        { answer: "ANTIFREEZE",
          score: 3,
        },
      ],
    },
    { question: "How many months does winter last?",
      factor: 2,
      answers: [
        { answer: "6",
          score: 27,
        },
        { answer: "7",
          score: 17,
        },
        { answer: "8",
          score: 6,
        },
        { answer: "9",
          score: 5,
        },
        { answer: "4",
          score: 2,
        },
        { answer: "10",
          score: 2,
        },
      ],
    },
    { question: "Name something that Americans have a different word for than Canadians.",
      factor: 2,
      answers: [
        { answer: "TUQUE",
          score: 27,
        },
        { answer: "POP",
          score: 17,
        },
        { answer: "PENCIL CRAYONS",
          score: 5,
        },
        { answer: "CHESTERFIELD",
          score: 5,
        },
        { answer: "MARKS",
          score: 3,
        },
      ],
    },
    { question: "Name a Prime Minister.",
      factor: 3,
      answers: [
        { answer: "STEPHEN HARPER",
          score: 27,
        },
        { answer: "JEAN CRETIEN",
          score: 16,
        },
        { answer: "PIERRE TRUDEAU",
          score: 15,
        },
        { answer: "JOHN A. MACDONALD",
          score: 6,
        },
        { answer: "BRIAN MULRONEY",
          score: 6,
        },
        { answer: "KIM CAMPBELL",
          score: 4,
        },
        { answer: "ROBERT BORDEN",
          score: 2,
        },
      ],
    },
    { question: "Name the best Canadian ski resort.",
      factor: 3,
      answers: [
        { answer: "WHISTLER",
          score: 35,
        },
        { answer: "LAKE LOUISE",
          score: 8,
        },
        { answer: "FERNIE",
          score: 8,
        },
        { answer: "BANFF",
          score: 7,
        },
        { answer: "SUNSHINE",
          score: 6,
        },
      ],
    },
  ],
  'Fast Money Canada 1': [
    { question: "Name a city in Canada that everyone has heard of.",
      factor: 1,
      answers: [
        { answer: "TORONTO",
          score: 39,
        },
        { answer: "VANCOUVER",
          score: 20,
        },
        { answer: "CALGARY",
          score: 7,
        },
        { answer: "OTTAWA",
          score: 6,
        },
        { answer: "EDMONTON",
          score: 2,
        },
      ],
    },
    { question: "Without looking it up, how much is $10.00 Canadian worth in U.S. dollars. (Rounded to the nearest 50 cents.)",
      factor: 1,
      answers: [
        { answer: "$10.00",
          score: 34,
        },
        { answer: "$9.50",
          score: 20,
        },
        { answer: "$9.00",
          score: 10,
        },
        { answer: "$11.00",
          score: 4,
        },
        { answer: "$10.50",
          score: 3,
        },
      ],
    },
    { question: "What temperature (in Celsius, rounded to the nearest 5 degrees) do you consider it to be cold outside?",
      factor: 1,
      answers: [
        { answer: "-20",
          score: 16,
        },
        { answer: "-10",
          score: 15,
        },
        { answer: "-15",
          score: 14,
        },
        { answer: "0",
          score: 12,
        },
        { answer: "10",
          score: 5,
        },
        { answer: "-30",
          score: 5,
        },
        { answer: "5",
          score: 3,
        },
        { answer: "-5",
          score: 3,
        },
      ],
    },
    { question: "Name a famous Canadian actress.",
      factor: 1,
      answers: [
        { answer: "PAMELA ANDERSON",
          score: 38,
        },
        { answer: "RACHEL MCADAMS",
          score: 20,
        },
        { answer: "ELLEN PAGE",
          score: 16,
        },
        { answer: "KIM CATTRALL",
          score: 8,
        },
        { answer: "ELISHA CUTHBERT",
          score: 6,
        },
      ],
    },
    { question: "Name a popular Canadian tourist attraction.",
      factor: 1,
      answers: [
        { answer: "NIAGARA FALLS",
          score: 24,
        },
        { answer: "BANFF",
          score: 17,
        },
        { answer: "CALGARY STAMPEDE",
          score: 9,
        },
        { answer: "WEM",
          score: 7,
        },
        { answer: "CN TOWER",
          score: 7,
        },
        { answer: "ROCKY MOUNTAINS",
          score: 4,
        },
      ],
    },
  ],
  'Canadian Family Feud 2': [
    { question: "Name a city you would not want to live in.",
      factor: 1,
      answers: [
        { answer: "TORONTO",
          score: 14,
        },
        { answer: "WINNIPEG",
          score: 12,
        },
        { answer: "REGINA",
          score: 6,
        },
        { answer: "YELLOWKNIFE",
          score: 5,
        },
        { answer: "FORT MCMURRAY",
          score: 4,
        },
        { answer: "VANCOUVER",
          score: 4,
        },
        { answer: "MONTREAL",
          score: 4,
        },
        { answer: "CALGARY",
          score: 4,
        },
        { answer: "SASKATOON",
          score: 3,
        },
        { answer: "DETROIT",
          score: 3,
        },
      ],
    },
    { question: "What is the biggest difference between Canadians and Americans?",
      factor: 1,
      answers: [
        { answer: "MORE POLITE",
          score: 18,
        },
        { answer: "SMARTER",
          score: 14,
        },
        { answer: "ACCENT",
          score: 9,
        },
        { answer: "FRIENDLIER",
          score: 6,
        },
        { answer: "LESS PATRIOTIC",
          score: 5,
        },
        { answer: "GUNS",
          score: 4,
        },
        { answer: "NO SHOES INSIDE",
          score: 3,
        },
        { answer: "MORE APOLOGETIC",
          score: 3,
        },
        { answer: "HEALTHCARE",
          score: 2,
        },
      ],
    },
    { question: "While camping, what animal are you most likely to see?",
      factor: 1,
      answers: [
        { answer: "DEER",
          score: 27,
        },
        { answer: "SQUIRREL",
          score: 16,
        },
        { answer: "BEAR",
          score: 10,
        },
        { answer: "GOPHER",
          score: 6,
        },
        { answer: "BIRD",
          score: 4,
        },
        { answer: "MOSQUITO",
          score: 3,
        },
        { answer: "MOOSE",
          score: 3,
        },
      ],
    },
    { question: "Name something that Canadians complain about.",
      factor: 2,
      answers: [
        { answer: "WEATHER",
          score: 40,
        },
        { answer: "AMERICANS",
          score: 17,
        },
        { answer: "TAXES",
          score: 5,
        },
        { answer: "FRENCH CANADIANS",
          score: 3,
        },
        { answer: "PRICE OF GAS",
          score: 2,
        },
        { answer: "POLITICS",
          score: 2,
        },
      ],
    },
    { question: "Name something people do with snow.",
      factor: 2,
      answers: [
        { answer: "BUILD A SNOWMAN",
          score: 28,
        },
        { answer: "SNOWBALL FIGHT",
          score: 9,
        },
        { answer: "BUILD FORTS",
          score: 8,
        },
        { answer: "SNOWBOARD/SKI",
          score: 7,
        },
        { answer: "SLEDDING",
          score: 5,
        },
        { answer: "EAT IT",
          score: 4,
        },
        { answer: "SHOVEL IT",
          score: 3,
        },
        { answer: "PEE IN IT",
          score: 2,
        },
      ],
    },
    { question: "Name a famous Canadian band.",
      factor: 2,
      answers: [
        { answer: "BARENAKED LADIES",
          score: 27,
        },
        { answer: "NICKELBACK",
          score: 21,
        },
        { answer: "RUSH",
          score: 5,
        },
        { answer: "OUR LADY PEACE",
          score: 3,
        },
        { answer: "GREAT BIG SEA",
          score: 3,
        },
        { answer: "THE TRAGICALLY HIP",
          score: 2,
        },
        { answer: "THE GUESS WHO",
          score: 2,
        },
        { answer: "SIMPLE PLAN",
          score: 2,
        },
        { answer: "BLUE RODEO",
          score: 2,
        },
        { answer: "BTO",
          score: 2,
        },
      ],
    },
    { question: "Name your favorite chocolate bar.",
      factor: 3,
      answers: [
        { answer: "KIT KAT",
          score: 10,
        },
        { answer: "MARS",
          score: 9,
        },
        { answer: "WUNDERBAR",
          score: 8,
        },
        { answer: "OH HENRY!",
          score: 7,
        },
        { answer: "EAT-MORE",
          score: 5,
        },
        { answer: "AERO",
          score: 5,
        },
        { answer: "TWIX",
          score: 4,
        },
        { answer: "CRISPY CRUNCH",
          score: 4,
        },
        { answer: "COFFEE CRISP",
          score: 4,
        },
      ],
    },
    { question: "What temperature (in Celsius, rounded to the nearest 5 degrees) do you consider it to be hot outside?",
      factor: 3,
      answers: [
        { answer: "30",
          score: 30,
        },
        { answer: "25",
          score: 29,
        },
        { answer: "20",
          score: 13,
        },
        { answer: "15",
          score: 3,
        },
        { answer: "35",
          score: 2,
        },
      ],
    },
  ],
  'Fast Money Canada 2': [
    { question: "Name your favorite sport.",
      factor: 1,
      answers: [
        { answer: "HOCKEY",
          score: 27,
        },
        { answer: "BASKETBALL",
          score: 17,
        },
        { answer: "VOLLEYBALL",
          score: 8,
        },
        { answer: "SOCCER",
          score: 5,
        },
        { answer: "GOLF",
          score: 5,
        },
        { answer: "SWIMMING",
          score: 2,
        },
        { answer: "BASEBALL",
          score: 2,
        },
      ],
    },
    { question: "Name one thing you dislike about living in Canada.",
      factor: 1,
      answers: [
        { answer: "WEATHER",
          score: 54,
        },
        { answer: "HIGHER PRICES",
          score: 8,
        },
        { answer: "DIVERSITY",
          score: 2,
        },
        { answer: "TAXES",
          score: 2,
        },
        { answer: "FRENCH LABELS",
          score: 2,
        },
      ],
    },
    { question: "Name your favorite NHL team.",
      factor: 1,
      answers: [
        { answer: "EDMONTON OILERS",
          score: 41,
        },
        { answer: "CALGARY FLAMES",
          score: 15,
        },
        { answer: "VAN. CANUCKS",
          score: 7,
        },
        { answer: "MONT. CANADIENS",
          score: 4,
        },
        { answer: "BOSTON BRUINS",
          score: 2,
        },
        { answer: "TOR. MAPLE LEAFS",
          score: 2,
        },
      ],
    },
    { question: "What is your favorite holiday?",
      factor: 1,
      answers: [
        { answer: "CHRISTMAS",
          score: 60,
        },
        { answer: "CANADA DAY",
          score: 6,
        },
        { answer: "HALLOWEEN",
          score: 3,
        },
        { answer: "EASTER",
          score: 3,
        },
        { answer: "THANKSGIVING",
          score: 2,
        },
      ],
    },
    { question: "Name something that is easier to do in Canada than it is to do in the States.",
      factor: 1,
      answers: [
        { answer: "GET HEALTHCARE",
          score: 30,
        },
        { answer: "WINTER SPORTS",
          score: 9,
        },
        { answer: "BE SAFE/DON'T GET SHOT",
          score: 3,
        },
        { answer: "FLY TO CUBA",
          score: 3,
        },
        { answer: "MATERNITY LEAVE",
          score: 2,
        },
        { answer: "GET EDUCATION",
          score: 2,
        },
      ],
    },
  ],
}

/*
    { question: "What is the most unique thing about Canada?",
      factor: 1,
      answers: [
        8 Eh
        6 Diversity
        6 Colourful Money/Loonies/Toonies
        4 People
        4 Landscape
        4 Friendly/Nice people
        3 Size/Large
        3 Diverse People
        3 Abundant Fresh water
        2 Weather
        2 Rocky Mountains
        2 Pop to Land ratio
        2 Maple Syrop
        2 Healthcare
        2 Flag
        2 Beavers
        1 Snow
        1 Oct Thanksgiving
        1 Niagra Falls
        1 Maple Leaf
        1 Longest SHoreline
        1 Long days and nights
        1 Igloos
        1 Hockey
        1 Every climate in one country
        1 Eskimoes
        1 Curling
        1 Cold
        1 Canadian Tire
        1 Bilingualism
        1 Apologetic People
        1 3 Oceans
      ],
    },
    { question: "Name something that is harder to do in Canada than it is to do in the States.",
      factor: 1,
      answers: [
        13 shop (online?)
        2 go to store late
        1 shop groceries 24/7
        1 get good deals
        1 find low prices
        1 extreme couponers
        13 buy a gun
        4 tan
        3 swim outside in december
        2 surfing
        2 sue somebodey
        2 netflix
        2 go to beach in winter
        2 get mortgage
        1 war
        1 trick or treat without snowsuit
        1 take peanut butter to school
        1 swim outside
        1 swim in ocean
        1 speed
        1 see a doctor
        1 scuba diving
        1 go to jail
        1 get arrested by homeland security
        1 get a passport
        1 get a breakfast burrito
        1 gamble
        1 find a job
        1 eat out cheap
        1 drive in winter
        1 develop property
        1 buy fireworks
        1 buy a car
        1 become a movie star
        1 be racist
        1 be outside
      ],
    },



    { question: "Name your favorite food.",
      factor: 1,
      answers: [
        { answer: "BEEF",
          score: 12,
        },
        { answer: "PIZZA",
          score: 9,
        },
        { answer: "LASAGNE",
          score: 8,
        },
        { answer: "POUTINE",
          score: 7,
        },
        { answer: "PASTA",
          score: 5,
        },
        { answer: "LOBSTER",
          score: 4,
        },
        { answer: "POTATOES",
          score: 4,
        },
        { answer: "SPAGHETTI",
          score: 4,
        },
        { answer: "CHICKEN",
          score: 3,
        },
        { answer: "CHOCOLATE",
          score: 3,
        },
      ],
    },
    */
